import Head from "next/head";
import Layout from "../components/Layout";
import Link from "next/link";
import Jumbotron from "react-bootstrap/Jumbotron";
import Button from "react-bootstrap/Button";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Jumbotron>
          <h1>My Next App</h1>
          <p>This is my Next.JS App</p>
          <p>
            <Link href="/posts">
              <Button variant="primary">Posts</Button>
            </Link>
          </p>
        </Jumbotron>
      </Layout>
    </div>
  );
}
